import { months, day, newMonth, dayTweeted } from './date.js';
const tweets = [
  {
    name: 'Max Code',
    pinnedIcon: '',
    pinnedText: '',
    img: './img/profile-pc.jpg',
    id: '@MaxCodeJourney',
    dateTweeted: `${dayTweeted}`,
    text: 'Starting from here, all these tweets are display dynamically.',
  },
  {
    name: 'Twitter',
    pinnedIcon: 'fas fa-retweet',
    pinnedText: 'Max Code retweeted',
    img: './img/twitter.jpg',
    id: '@twitter',
    dateTweeted: `${dayTweeted}`,
    text: 'This really Look awesome! Very well done, we are looking forward to working with you Max ',
  },
  {
    name: 'Max Code',
    pinnedIcon: '',
    pinnedText: '',
    img: './img/profile-pc.jpg',
    id: '@MaxCodeJourney',
    dateTweeted: `${dayTweeted}`,
    text: 'At the top of the page where the total number of tweets are displayed, that number is also set dynamically.',
  },
  {
    name: 'Max Code',
    pinnedIcon: '',
    pinnedText: '',
    img: './img/profile-pc.jpg',
    id: '@MaxCodeJourney',
    dateTweeted: `${dayTweeted}`,
    text: 'Although it is not exactly like I wanted, to show the date of the tweets I also use javascript on the dinamic tweets.',
  },
  {
    name: 'Max Code',
    pinnedIcon: '',
    pinnedText: '',
    img: './img/profile-pc.jpg',
    id: '@MaxCodeJourney',
    dateTweeted: `${dayTweeted}`,
    text: 'This project is also responsive I you can see different layouts depending on the screen size.',
  },
  {
    name: 'Max Code',
    pinnedIcon: '',
    pinnedText: '',
    img: './img/profile-pc.jpg',
    id: '@MaxCodeJourney',
    dateTweeted: `${dayTweeted}`,
    text: 'Some of the buttons do something when you click them, like the ones under the profile or icons under tweets and the Follow buttons. ',
  },
  {
    name: 'Max Code',
    pinnedIcon: '',
    pinnedText: '',
    img: './img/profile-pc.jpg',
    id: '@MaxCodeJourney',
    dateTweeted: `${dayTweeted}`,
    text: 'I have used mostly GRID layout in this project, use position absolute to place the search icon under search bar and position fixed for the navbar. ',
  },
  {
    name: 'Max Code',
    pinnedIcon: '',
    pinnedText: '',
    img: './img/profile-pc.jpg',
    id: '@MaxCodeJourney',
    dateTweeted: `${dayTweeted}`,
    text: 'I am sure I wanted to write more details about this project but right now I cannot remember everything I wanted to say. So maybe I will come later and Tweet it. See you!!!',
  },
];
export default tweets;
